use utf8;
package Unterwegs::Model::UnterwegsDB;

# ABSTRACT: Model for Unterwegs database

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Unterwegs::Schema',
);

=head1 NAME

Unterwegs::Model::UnterwegsDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Unterwegs>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Unterwegs::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

sca21002

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
